### ISSUE TITLE
Integrating with an authentication management system other than Keycloak

### ISSUE THREAD

**Issue by reshmi-nair** [Sunbird-Lern/sunbird-lms-service#1177]
### Project Details
User account creation and management, user login as well as platform administration capabilities is powered by the User-Org Service of Sunbird Lern Building Block.
This component enables the users to create accounts to save their platform preferences, access relevant content based on their preferences etc. Users with accounts on the system who login also get access to richer platform features such as Courses and Learner passbook.
Platform administrators can be granted capabilities to manage user roles on the platform, as well as manage platform master data (eg. Location data, Framework values etc.)
Configure the platform to allow for user logins via various mechanisms including username/ password, Google login or single sign-on with other approved systems.

### Features to be implemented
UserOrg currently supports authentication using Keycloak 7.0.1. This project is to check whether other authentication system can be used instead of Keycloak.

### Learning Path
**Complexity**
Medium

**Skills Required**
Java

**Name of Mentors:**
Hari P - [[harip@ilimi.in](mailto:harip@ilimi.in))

**Project size**
TBD

**Product Set Up**
Instruction to install userorg service is available [here](https://github.com/Sunbird-Lern/sunbird-lms-service/tree/release-5.3.0)

**Acceptance Criteria**
Replace keycloak with any other authentication system , also generalise the authentication flow.

### Milestones
 
- [ ] Understanding the requirements
- [ ]  Understanding Keycloak and user-org integration
- [ ]  Setting up the service
- [ ]  Understanding the authentication flow
- [ ]  Checking login feasibility with other authentication systems

**Comment by AdityaGore19** [comment]
hello harip@ilimi.in , I would like to contribute to this project. I am familiar with java and a few authentication softwares and I would really appreciate your guidance on the project.

**Comment by keval-kanp-1011** [comment]
harip@ilimi.in,  As I'm familiar to use Authentication System with Java & Kotlin , I would like to contribute to project and want you to be the mentor

**Comment by ayush27prasad** [comment]
Hi, the issue seems to align with my proficiency in Java development, given that I also have the experience of development concerning Web Security. Would appreciate you guidance to work on this issue. Regards.

**Comment by Jayaprakash8887** [comment]
At present Keycloak is used as authentication management system. Details can be found at https://project-sunbird.atlassian.net/wiki/spaces/DevOps/pages/3271229627/Keycloak+on+Sunbird
