### ISSUE TITLE
Keycloak upgrade from version 7.0.1 to 20.0.0

### ISSUE THREAD

**Issue by reshmi-nair** [Sunbird-Lern/sunbird-lms-service#1178]
### Project Details
User account creation and management, user login as well as platform administration capabilities is powered by the User-Org Service of Sunbird Lern Building Block.
This component enables the users to create accounts to save their platform preferences, access relevant content based on their preferences etc. Users with accounts on the system who login also get access to richer platform features such as Courses and Learner passbook.
Platform administrators can be granted capabilities to manage user roles on the platform, as well as manage platform master data (eg. Location data, Framework values etc.)
Configure the platform to allow for user logins via various mechanisms including username/ password, Google login or single sign-on with other approved systems.

### Features to be implemented
UserOrg currently supports authentication using Keycloak 7.0.1. An upgrade from 7.0.1 to 20.0.0 version needs to be done.

### Learning Path
**Complexity**
Medium

**Skills Required**
Java

**Name of Mentors:**
Hari P - [[harip@ilimi.in](mailto:harip@ilimi.in))

**Project size**
TBD

**Product Set Up**
Instruction to install userorg service is available [here](https://github.com/Sunbird-Lern/sunbird-lms-service/tree/release-5.3.0) for integration testing with keycloak.

**Acceptance Criteria**
Keycloak version 20.0.0 should be up and running with user-org service.

### Milestones 

- [ ] Understanding the requirements
- [ ]  Understanding Keycloak and user-org integration
- [ ]  Setting up the service
- [ ]  Understanding the authentication flow
- [ ]  Documenting the upgrade

**Comment by jineshpatel2002** [comment]
Hello author and mentor I am interested to contribute on this project .

**Comment by Tarunoid** [comment]
Hello sir/madam , I am interested in contributing to this project.

**Comment by Ganesh-hacker** [comment]
Hello sir/madam ,

 I am interested in contributing to this project.

**Comment by devam2001** [comment]
Hello Sir/Madam,

I am interested in contributing to this project as my skillsets are matching with the requirement of the project and this would also help me to gain meaningful experience in open source .

**Comment by nitin1chandani** [comment]
Hi @Hari-stackroute 
I have thoroughly reviewed the project details for the "UserOrg Service Upgrade" and I am excited to work on this project. I have gone through the project requirements and the integration of Keycloak with the user-org service.

I want to express my interest and proficiency in Java, which is the required skill for this project. I have experience working with Java for DSA and I am confident in my ability to handle the upgrade from Keycloak version 7.0.1 to version 20.0.0.

I am planning to submit my application soon, outlining my approach and timeline for the upgrade process. I am eager to contribute to this project and I look forward to the opportunity of working with you.

Thankyou !!

**Comment by milindmohan25** [comment]
i am interested

**Comment by Jayaprakash8887** [comment]
https://project-sunbird.atlassian.net/wiki/spaces/DevOps/pages/3271229627/Keycloak+on+Sunbird

**Comment by Jayaprakash8887** [comment]
https://github.com/Sunbird-Lern/sunbird-lms-service/blob/release-5.3.0/keycloak_local_setup/keycloak_local_setup.md

**Comment by prateek2k2** [comment]
Hello author and mentor I'm interested in this project

**Comment by madhu814** [comment]
I am interested in contributing in this project. Can anyone tell is there any good-first-issue in this project.

**Comment by ShubhamKrSingh21** [comment]
Hey @Hari-stackroute  I am Shubham Kumar Singh, a third-year undergraduate student majoring in Information Technology at the Institute of Engineering & Management, Kolkata which is among the elite universities in India. After conducting a comprehensive examination of the project specifics regarding the "UserOrg Service Upgrade," I am enthusiastic about being involved in this undertaking. I have carefully assessed the project's prerequisites, including the incorporation of Keycloak into the user-org service. As an undergraduate who has always been deeply fascinated by the applications of mathematics and computer science, I find my research interest gravitating towards the study of Artificial Intelligence and Java Developer. I've a wide experience in Java of 5+ years and 3+ years at Machine Learning. While this might be a very broad field I am particularly oriented towards Natural Language Processing, Computer Vision, ROI Perception, and Reinforcement Learning. I have explored this subject in-depth and would like to utilize it effectively to address more real-world challenges. I am fortunate enough to acquire a more comprehensive understanding of Al from both graduate-level machine learning courses and participation in research work. While the former has introduced me to neural net approaches that simulate the biological processes of learning and the unsupervised learning methods, the latter is primarily focusing on Bayesian Inference, Reinforcement Learning and Al Planning. I regard Al as a field that never seems to reach full potential as human ingenuity frequently leads to considerable improvements in the study and design of intelligent agents and such realization has also led me to keep exploring the endless possibilities of Al.

Gmail - shubham6418814@gmail.com

Resume - https://drive.google.com/file/d/1-Jih0xJDHNPBvrCxoQ3lOyZvo_N3Iai8/view?usp=drivesdk

LinkedIn - https://www.linkedin.com/in/shubham-kumar-singh-356427206

GitHub - https://github.com/ShubhamKrSingh21

Portfolio - https://shubhamkumarsingh.netlify.app/

**Comment by Jayaprakash8887** [comment]
> https://github.com/Sunbird-Lern/sunbird-lms-service/blob/release-5.3.0/keycloak_local_setup/keycloak_local_setup.md

Please refer to this documentation for local setup. Updated documentation on Jun 16.
